#!/usr/bin/env node
/*
 * generate_yurs_map.mjs — Generate a YURS Map.py from movemap_config.mjs
 *
 * Usage:
 *   node scripts/generate_yurs_map.mjs            # writes dist/yurs/Map.py
 *   node scripts/generate_yurs_map.mjs --print    # print to stdout only
 *
 * The generated Map.py is a drop-in replacement for the Map.py file inside
 * your YURS (Yaeltex Universal Remote Script) installation. Copy it to:
 *
 *   macOS:   ~/Music/Ableton/User Library/Remote Scripts/YaeltexUniversal/Map.py
 *   Windows: %USERPROFILE%\Documents\Ableton\User Library\Remote Scripts\YaeltexUniversal\Map.py
 *
 * Then restart Ableton Live.
 *
 * YURS source: https://github.com/aumhaa/yaeltex_universal
 */

import { createRequire } from 'module';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

// Dynamic import so this script can live outside the src/ tree
const configUrl = new URL('../src/config/movemap_config.mjs', import.meta.url);
const { movemapConfig } = await import(configUrl.href);

const p = movemapConfig.yursProfile;
const ch = p.midiChannel; // 0-indexed MIDI channel

function pyList(arr) {
    return `[${arr.join(', ')}]`;
}

const map = `# Generated by scripts/generate_yurs_map.mjs
# Source: src/modules/movemap/config/movemap_config.mjs
# DO NOT EDIT — regenerate by running: node scripts/generate_yurs_map.mjs
#
# Drop this file into your YURS installation directory as Map.py, then
# restart Ableton Live. All CC/note assignments will match MoveMap's config.
#
# YURS source: https://github.com/aumhaa/yaeltex_universal

# ── Primary control channel (MIDI channel ${ch + 1}, 0-indexed: ${ch}) ─────────────────
CHANNEL = ${ch}

# ── Mute / Solo / Arm (note-based, sent/received on CHANNEL) ──────────────
MUTE_NOTES   = ${pyList(p.notes.mute)}
MUTE_CHANNEL = CHANNEL

SOLO_NOTES   = ${pyList(p.notes.solo)}
SOLO_CHANNEL = CHANNEL

ARM_NOTES    = ${pyList(p.notes.arm)}
ARM_CHANNEL  = CHANNEL

# ── Volume / Send A (CC-based) ─────────────────────────────────────────────
VOLUME_CCS    = ${pyList(p.ccs.volume)}
VOLUME_CHANNEL = CHANNEL

SENDA_CCS    = ${pyList(p.ccs.sendA)}
SENDA_CHANNEL = CHANNEL

# Send B–H: not mapped by MoveMap by default. Define if your YURS setup uses them.
SENDB_CCS    = list(range(16, 32))
SENDB_CHANNEL = CHANNEL
SENDC_CCS    = list(range(32, 48))
SENDC_CHANNEL = CHANNEL
SENDD_CCS    = list(range(48, 64))
SENDD_CHANNEL = CHANNEL
SENDE_CCS    = list(range(64, 80))
SENDE_CHANNEL = CHANNEL
SENDF_CCS    = list(range(80, 96))
SENDF_CHANNEL = CHANNEL
SENDG_CCS    = list(range(96, 112))
SENDG_CHANNEL = CHANNEL
SENDH_CCS    = list(range(112, 128))
SENDH_CHANNEL = CHANNEL

# ── Master / Return ────────────────────────────────────────────────────────
MASTER_VOLUME_CC      = ${p.ccs.masterVolume}
MASTER_VOLUME_CHANNEL = CHANNEL

RETURN_VOLUME_CCS     = [${p.ccs.returnVolume}]
RETURN_VOLUME_CHANNEL = CHANNEL

# ── Device macros / parameters ─────────────────────────────────────────────
PARAMETER_CCS      = ${pyList(p.ccs.macros)}
PARAMETER_CHANNEL  = CHANNEL
EXTENDED_PARAM_DIALS = False   # True = 16 dials; False = 8 dials (matches MoveMap)

# ── Track select / crossfade (YURS defaults, not mapped by MoveMap) ────────
SELECT_NOTES           = list(range(48, 64))
SELECT_CHANNEL         = CHANNEL
CROSSFADE_ASSIGN_NOTES = list(range(64, 80))
CROSSFADE_ASSIGN_CHANNEL = CHANNEL

# ── Pan (not mapped by MoveMap — using YURS default) ──────────────────────
PAN_CCS    = list(range(16, 32))
PAN_CHANNEL = CHANNEL

# ── Selected sends / selected track params (YURS internal routing) ─────────
SELECTED_SENDS_CCS     = list(range(0, 8))
SELECTED_SENDS_CHANNEL = CHANNEL

SELECTEDTRACK_PARAMETER_CCS     = list(range(0, 64))
SELECTEDTRACK_PARAMETER_CHANNEL = CHANNEL

# ── Per-track parameter dials (tracks 1–8) ────────────────────────────────
TRACK1_PARAMETER_CCS  = list(range(0, 64))
TRACK1_PARAMETER_CHANNEL = CHANNEL
TRACK2_PARAMETER_CCS  = list(range(0, 64))
TRACK2_PARAMETER_CHANNEL = CHANNEL
TRACK3_PARAMETER_CCS  = list(range(0, 64))
TRACK3_PARAMETER_CHANNEL = CHANNEL
TRACK4_PARAMETER_CCS  = list(range(0, 64))
TRACK4_PARAMETER_CHANNEL = CHANNEL
TRACK5_PARAMETER_CCS  = list(range(0, 64))
TRACK5_PARAMETER_CHANNEL = CHANNEL
TRACK6_PARAMETER_CCS  = list(range(0, 64))
TRACK6_PARAMETER_CHANNEL = CHANNEL
TRACK7_PARAMETER_CCS  = list(range(0, 64))
TRACK7_PARAMETER_CHANNEL = CHANNEL
TRACK8_PARAMETER_CCS  = list(range(0, 64))
TRACK8_PARAMETER_CHANNEL = CHANNEL

# ── Navigation ─────────────────────────────────────────────────────────────
TRACK_SELECT_CC        = 115
TRACK_SELECT_CHANNEL   = CHANNEL
SCENE_SELECT_CC        = 116
SCENE_SELECT_CHANNEL   = CHANNEL
TRACK_BANK_NAV_CC      = 113
TRACK_BANK_NAV_CHANNEL = CHANNEL
SCENE_BANK_NAV_CC      = 114
SCENE_BANK_NAV_CHANNEL = CHANNEL

# ── Transport / tempo ──────────────────────────────────────────────────────
TEMPO_CONTROL_CC  = 124
CROSSFADER_CC     = 125
CUE_VOLUME_CC     = 126

# ── Master track / device navigation notes ────────────────────────────────
MASTER_SELECT_NOTE         = 117
MASTER_SELECT_CHANNEL      = CHANNEL
DEVICE_NAV_PREV            = 118
DEVICE_NAV_NEXT            = 119
DEVICE_RANDOMIZE_MACRO_NOTE = 120
DEVICE_ADD_MACRO_NOTE      = 121
DEVICE_DELETE_MACRO_NOTE   = 122
DEVICE_PREV_MACRO_NOTE     = 123
DEVICE_NEXT_MACRO_NOTE     = 124
DEVICE_BANK_PREV_NOTE      = 125
DEVICE_BANK_NEXT_NOTE      = 126
PARAMETER_ON_OFF_NOTE      = 127

# ── Session grid ───────────────────────────────────────────────────────────
SESSION_BOX_SIZE = (8, 4)   # 8 tracks × 4 scenes
`;

const printOnly = process.argv.includes('--print');

if (printOnly) {
    process.stdout.write(map);
} else {
    const outDir = join(repoRoot, 'dist', 'yurs');
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, 'Map.py');
    writeFileSync(outPath, map, 'utf8');
    console.log(`Generated: ${outPath}`);
    console.log(`MIDI channel: ${ch + 1} (0-indexed: ${ch})`);
    console.log(`Mute notes:   ${p.notes.mute.join(', ')}`);
    console.log(`Solo notes:   ${p.notes.solo.join(', ')}`);
    console.log(`Arm notes:    ${p.notes.arm.join(', ')}`);
    console.log(`Volume CCs:   ${p.ccs.volume.join(', ')}`);
    console.log(`Send A CCs:   ${p.ccs.sendA.join(', ')}`);
    console.log(`Master CC:    ${p.ccs.masterVolume}  Return CC: ${p.ccs.returnVolume}`);
    console.log(`Macro CCs:    ${p.ccs.macros.join(', ')}`);
}
